name: API Tests
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: code/package-lock.json
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Clone nmos-testing Repository
      run: |
        git clone https://github.com/AMWA-TV/nmos-testing.git nmos-testing

    - name: Install nmos-testing Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r nmos-testing/requirements.txt

    - name: Verify Python and Packages
      run: |
        python --version
        pip --version
        pip list
    
    - name: Install dependencies
      run: npm ci
      working-directory: code

    - name: Get Local IP Address
      run: |
        local_ip=$(hostname -I | awk '{print $1}')
        echo "Local IP Address: $local_ip"
        echo "LocalIPAddress=$local_ip" >> $GITHUB_ENV

    - name: Update config.json with LocalIPAddress and work_without_registry
      run: |
        CONFIG_FILE="code/config/config.json"

        # Check that LocalIPAddress is set
        if [ -z "$LocalIPAddress" ]; then
          echo "LocalIPAddress is not set"
          exit 1
        fi

        # Use jq to update the two keys
        jq --arg ip "$LocalIPAddress" '.work_without_registry = true | .address = $ip' "$CONFIG_FILE" > "$CONFIG_FILE.tmp"
        mv "$CONFIG_FILE.tmp" "$CONFIG_FILE"

        echo "Updated $CONFIG_FILE:"
        cat "$CONFIG_FILE"

    - name: Start Node.js App
      run: |
        cd code
        npm run build-and-start &
        echo $! > ../node_pid.txt
        sleep 10  # give the server time to start

    - name: Run NMOS Test Suite
      working-directory: nmos-testing
      run: |
        echo "Using IP: $LocalIPAddress"
        mkdir -p ../test_results
        python nmos-test.py suite IS-12-01 \
          --host $LocalIPAddress $LocalIPAddress null null \
          --port 6789 6789 0 0 \
          --version v1.3 v1.0 v1.0 v1.0 \
          --urlpath null /x-nmos/ncp/v1.0/ws null null \
          --output ../test_results/is_12_01_results.json


    - name: Stop Node.js App
      if: always()
      run: |
        if [ -f node_pid.txt ]; then
          kill $(cat node_pid.txt) || true
        fi
