name: Render
on:
  workflow_dispatch:

  push:
    branches:
        - main
        - 'publish-*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2.5.0

    - name: Login to DockerHub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build
      uses: docker/build-push-action@v4.0.0
      with:
        context: ./code
        builder: ${{ steps.buildx.outputs.name }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: amwa/nmos-device-control-mock:latest
