name: PR Checks
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: code/package-lock.json
    
    - name: Install dependencies
      run: npm ci
      working-directory: code
    
    - name: Lint
      run: npm run lint
      working-directory: code
    
    - name: Type check
      run: npm run type-check
      working-directory: code
    
    - name: Build
      run: npm run build-ci
      working-directory: code
